---
title: "Lab 5"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.1 and 1.2

95% CI formula again: $mean \pm 1.96\frac{standard\ deviation}{number\ of\ obs.}$


```{r, eval = FALSE, echo = FALSE, message= FALSE}
library(tidyverse)
icelandic <- read.csv("https://goo.gl/7gIjvK")
icelandic %>% 
  group_by(aspiration, speaker) %>%
  summarise(mean = mean(vowel.dur),
            CI = 1.96*sd(vowel.dur)/sqrt(length(vowel.dur)))
```

## 1.3
```{r, eval = FALSE, echo = FALSE}
icelandic %>% 
  group_by(aspiration, speaker) %>%
  summarise(mean = mean(vowel.dur),
            CI = 1.96*sd(vowel.dur)/sqrt(length(vowel.dur))) %>% 
    ggplot(aes(aspiration, mean))+
  geom_point()+
  geom_errorbar(aes(ymin= mean-CI,
                    ymax = mean+CI), width = 0.3)+
  facet_wrap(~speaker)+
  labs(title = "Mean vowel duration with 95% confidence interval",
       caption = "Data from (Coretta 2017)")
  
```

## 1.4
```{r, eval = FALSE, echo = FALSE}
icelandic %>% 
  ggplot(aes(vowel.dur, fill = aspiration, color = aspiration))+
  geom_density(alpha = 0.4)+
  geom_rug()+
  facet_wrap(~speaker)+
  labs(title = "Vowel duration density plot",
       caption = "Data from (Coretta 2017)",
       x = "vowel duration")
```
```{r, eval = FALSE, echo = FALSE}
icelandic %>% 
  ggplot(aes(sample = vowel.dur, color = aspiration))+
  geom_qq()+
  facet_wrap(~speaker, scales = "free")+
  labs(title = "Vowel duration density plot",
       caption = "Data from (Coretta 2017)")
```

## 1.6-1.10

```{r, eval = FALSE, echo = FALSE}
table(icelandic$speaker)
icelandic_1 <- subset(icelandic,speaker == "brs02")
icelandic_2 <- subset(icelandic,speaker == "bte03")
icelandic_3 <- subset(icelandic,speaker == "jj04")
icelandic_4 <- subset(icelandic,speaker == "shg05")
icelandic_5 <- subset(icelandic,speaker == "tt01")
t.test.results_1 <- t.test(vowel.dur~aspiration, icelandic_1)
t.test.results_2 <- t.test(vowel.dur~aspiration, icelandic_2)
t.test.results_3 <- t.test(vowel.dur~aspiration, icelandic_3)
t.test.results_4 <- t.test(vowel.dur~aspiration, icelandic_4)
t.test.results_5 <- t.test(vowel.dur~aspiration, icelandic_5)
```

## 1.11-1.15
```{r, eval = FALSE, echo = FALSE}
library(lsr)
cohensD(vowel.dur~aspiration, data = icelandic_1)
cohensD(vowel.dur~aspiration, data = icelandic_2)
cohensD(vowel.dur~aspiration, data = icelandic_3)
cohensD(vowel.dur~aspiration, data = icelandic_4)
cohensD(vowel.dur~aspiration, data = icelandic_5)
```

## 1.16
```{r, eval = FALSE, echo = FALSE}
power.t.test(n = length(icelandic_4$vowel.dur),
             sd = sd(icelandic_4$vowel.dur),
             delta = t.test.results_4$estimate[2] - t.test.results_4$estimate[1],
             sig.level = 0.05,
             type = "two.sample")
```

