---
title: "Lab 6: χ², Fisher Test, correlations"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 1.1
```{r, include = FALSE}
chisq.test(matrix(c(5485, 8318, 15913, 8259), nrow = 2))
```

### 2.1
```{r, include = FALSE}
ru <- read.csv("http://goo.gl/KljqjU")
table(ru)
chisq.test(table(ru))$expected > 5
chisq.test(table(ru))
```

### 2.2
```{r, include = FALSE}
pl <- read.csv("http://goo.gl/xNozm2")
table(pl)
chisq.test(table(pl))$expected > 5
fisher.test(table(pl))
```


### 3.1-3.2
```{r, include = FALSE}
df <- data.frame(
  no_adpositions = c(11, 30),
  prepositions = c(5, 511),
  postpositions = c(59, 576),
  no_dominant_order = c(2, 58),
  inpositions = c(0, 8))

chisq.test(df)$expected < 5

# answer: inpositions, no_adpositions, no_dominant_order

fisher.test(df)
```

### 4.1
```{r, message= FALSE, include = FALSE}
library(tidyverse)
df <- read.csv("http://goo.gl/txmyO9", sep = "\t")
df[,-1] %>% 
  cor() ->
  m
m

# better View
m %>% 
  as.table() %>% 
  as.data.frame() %>% 
  arrange(desc(Freq))

# "kendall"
df[,-1] %>% 
  cor(., method = "kendall") %>% 
  as.table() %>% 
  as.data.frame() %>% 
  arrange(desc(Freq))

# "spearman"
df[,-1] %>% 
  cor(., method = "spearman") %>% 
  as.table() %>% 
  as.data.frame() %>% 
  arrange(desc(Freq))
```


