---
title: "Lab 10. Mixed effect models"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include=FALSE)
```

## [Assignment link](https://goo.gl/forms/uY2wGxkZrAauIgzG2)

```{r, message= FALSE, include=TRUE}
library(tidyverse); library(lingtypology); library(lme4)
```

### 1. Consonants and vowels
```{r, include=TRUE}
lapsyd <- read.csv("https://goo.gl/eD4S5n")
map.feature(lapsyd$name, features = lapsyd$area, 
              label = lapsyd$name,
              label.hide = TRUE)
```
```{r}
fit1 <- lm(count_vowel~count_consonant, data = lapsyd)
summary(fit1)

lapsyd$model1 <- predict(fit1)

lapsyd %>% 
  ggplot(aes(count_consonant, count_vowel))+
  geom_point()+
  geom_line(aes(count_consonant, model1), color = "blue")+
  labs(x = "number of consonants",
       y = "number of vowels",
       caption = "data from LAPSyD")

fit2 <- lmer(count_vowel ~ count_consonant + (1|area), data = lapsyd)
summary(fit2)

lapsyd$model2 <- predict(fit2)

lapsyd %>% 
  ggplot(aes(count_consonant, count_vowel))+
  geom_point()+
  geom_line(aes(count_consonant, model2, color = area))+
  labs(x = "number of consonants",
       y = "number of vowels",
       caption = "data from LAPSyD")

fit3 <- lmer(count_vowel ~ count_consonant + (1+count_consonant|area), data = lapsyd)
summary(fit3)

lapsyd$model3 <- predict(fit3)

lapsyd %>% 
  ggplot(aes(count_consonant, count_vowel))+
  geom_point()+
  geom_line(aes(count_consonant, model3, color = area))+
  labs(x = "number of consonants",
       y = "number of vowels",
       caption = "data from LAPSyD")

fit4 <- lmer(count_vowel ~ count_consonant + (0+count_consonant|area), data = lapsyd)
summary(fit4)

lapsyd$model4 <- predict(fit4)

lapsyd %>% 
  ggplot(aes(count_consonant, count_vowel))+
  geom_point()+
  geom_line(aes(count_consonant, model4, color = area))+
  labs(x = "number of consonants",
       y = "number of vowels",
       caption = "data from LAPSyD")

fit5 <- lmer(count_vowel ~ count_consonant + (1|area) + (0+count_consonant|area), data = lapsyd)
summary(fit5)

lapsyd$model5 <- predict(fit5)

lapsyd %>% 
  ggplot(aes(count_consonant, count_vowel))+
  geom_point()+
  geom_line(aes(count_consonant, model5, color = area))+
  labs(x = "number of consonants",
       y = "number of vowels",
       caption = "data from LAPSyD")
```

