---
title: Intro to R and RStudio. Vectors. Dataframes. Packages.
---
```{r}
# calculator
2+2
27/3
3^9
3**9
3**9+1
3**(9+1)
sum(1, 2, 5,29, 43)
prod(1, 2, 5,29, 43)
50 %% 3
abs(-53)
factorial(20)
pi
exp(1)
choose(7, 3)
27^(1/3)
log(4)
log10(39)
34+2i
9^(1/2)
27^(1/3)
```

### General units
```{r}
typeof(3)
typeof(5L)
typeof("Hi all")
typeof(43 + 4i)
typeof(TRUE)
typeof(F)
```

### vectors
```{r}
1:40
40:1*10
c("a", "b", "ку-ку")
c("a", "b", "ку-ку", 2)
c(T, F, T, T)
c(T, F, T, T, 1)
sum(c(T, F, T, T))

sum(1:50 > 30)

1:25*2-1

seq(2, 10, 2)
seq(from = 2, to = 20, by = 3)
seq(by = 3, to = 20, from = 2)
seq(b = 3, t = 20, f = 2)
seq(2, 20, 3)

letters
LETTERS
month.abb
month.name

sample(1:6, size = 2)
sample(1:6, size = 2, replace = T)

set.seed(19012017)
sample(1:6, size = 2, replace = T)
sample(1:6, size = 2, replace = T)

runif(10, min = 20, max = 50)
```

### Variables
```{r}
a <- 1:19
a
a+1
a
a <- a + 1
a
b <- a
b <- b + 100
a

a = 1:19 # not cool

length(a)

length("1234567890")
nchar("1234567890")

a <- c(Masha = 5, Vanya = 7, Anya = 4, Masha = 3)
a
a <- c('Masha' = 1:5, 'Vanya' = 7, 'Anya' = 4, 'Masha' = 3)
a
a["Vanya"]
a["Masha"]
```

### Matrix
```{r}
matrix(1:10)
matrix(1:10, nrow = 5)
matrix(1:10, ncol = 5)
m <- matrix(1:10)
dim(m)
dim(m) <- c(2, 5)
m
```

### Lists
```{r}
a <- list(a = letters,
     b = 1:20,
     c = c(T, T, F, F, F))
a
```
### Dataframe
```{r}
df <- data.frame(length = c(1.78, 74, 89, 23),
                 weight = c(40, 50, 20, 90), 
                 names = c("Dyumovochka", "Masha", "Tanya", "Stepa"),
                 get.up.early = c(T, T, F, F))
df

mtcars
#? cars
apropos("date")
```

### Logic
```{r}
"mama" == "mama"
"mama" == "tama"
"mama" != "tama"
"mama" > "tama"
"mama" < "tama"
"mama" < c("tama", "bama")
3 <= 5
10 >= 100
10 > -Inf
10 < Inf
2+2 == 4
10/3 == 100/3-30

TRUE & FALSE
TRUE | FALSE
TRUE | c(FALSE, TRUE)
TRUE & c(FALSE, TRUE)
```

### Indexing
```{r}
a <- 1:100
a[45]

a <- c(masha = 1:100)
a["masha43"]

a[a > 40]

mtcars$cyl[17]
mtcars[3, 7] # first rows, second columns
mtcars[mtcars$cyl !=6, ]
mtcars[mtcars$cyl !=6, 1:3]
rownames(mtcars[mtcars$cyl !=6, ])[1:3]

# View(mtcars)
d <- mtcars
```
### Library
```{r}
#install.packages("lingtypology")
library(lingtypology)
map.feature(c("Russian", "Abaza", "Adyghe"))
```

### Functions
```{r}
a <- 2
if(a > 3){
  print("hello")
} else {
  print("bye")
}



```

