---
title: "Data manipulation and visualization"
Lab 2
---

### dplyr

Data frame "flights"
```{r, warning=FALSE, message=FALSE}
# install.packages("nycflights13")
library(nycflights13)
head(flights)
dim(flights)
```
Some useful dplyr functions: filter(), slice(), arrange(), select(), distinct(), mutate(), summarise(), sample()
```{r, warning=FALSE, message=FALSE}
filter(flights, month == 1, day == 1) # cf. Basic R: flights[flights$month == 1 & flights$day == 1, ]
```
(?) Find out how many flights there were on July 4? Dec 31? Dec 32? Use "|" to look for more than one date.
```{r, warning=FALSE, message=FALSE}
arrange(flights, year, month, day, desc(arr_delay)) # cf. Basic R: flights[order(flights$arr_delay, decreasing = TRUE), ]
flight1 <- select(flights, year, month, day)
```


### tidyverse

Data frame "words"
```{r, warning=FALSE, message=FALSE}
# install.packages("tidyverse")
# or (if you have any problem with installation) use github repository:
## install.packages("devtools")
# library(devtools)
# install_github("tidyverse/tidyverse") # given that https://github.com/tidyverse/tidyvers is a path, quotation marks are obligatory
library(tidyverse)
words <- read_csv("https://goo.gl/a4xNwj")
words <- c(words$trans_english, words$trans_russian)
words <-sapply(words, function(x){unlist(strsplit(x, ",| "))[1]})
```
Some useful functions: `nchar()`,  `grepl()`
```{r, echo = FALSE, warning=FALSE, message=FALSE}
n_char <- nchar(words)
n_vowels <- sapply(words, function(x){
sum(grepl("e|u|i|o|a|у|е|ы|а|о|э|я|и|ю|ё",
     substring(x, 1:nchar(x), 1:nchar(x))))})
language <- rep(c("eng", "rus"), each = 1310)
words_df <- data.frame(words, n_char, n_vowels, language)
rm(n_char, n_vowels, language)
```
```{r, echo = FALSE}
words_df %>%
  select(language, n_char) %>% 
  mutate(n_char = factor(n_char)) %>% 
  group_by(n_char, language) %>% 
  summarise(number = n()) %>% 
  ggplot(aes(x = n_char,y = number, fill = language))+
  geom_bar(stat = "identity", position = "dodge")+
  theme_bw()+
  xlab("number of characters")+
  ylab("number of words")+
  labs(title = "Number of characters in Russian and English words",
          caption = "data is from http://ids.clld.org/")
```

Here is a string that we will treat as vowels:
```{r, echo= F}
"e|u|i|o|a|у|е|ы|а|о|э|я|и|ю|ё"
```

```{r,echo=FALSE}
words_df %>%
  select(language, n_vowels) %>% 
  mutate(n_vowels = factor(n_vowels)) %>% 
  group_by(n_vowels, language) %>% 
  summarise(number = n()) %>% 
  ggplot(aes(x = n_vowels,y = number))+
  geom_bar(stat = "identity", position = "dodge")+
  theme_bw()+
  facet_wrap(~language)+
  xlab("number of vowels")+
  ylab("number of words")+
  labs(title = "Number of vowels in Russian and English words",
          caption = "data is from http://ids.clld.org/")
```

```{r,echo=FALSE}
words_df %>%
  select(language, n_vowels) %>% 
  mutate(n_vowels = factor(n_vowels)) %>% 
  group_by(n_vowels, language) %>% 
  summarise(number = n()) ->
  data
data2 <- data[,-2]

data %>% 
  ggplot(aes(x = n_vowels,y = number, fill = language))+
  geom_bar(data = data2, stat = "identity", fill = "lightgrey")+
  geom_bar(stat = "identity", position = "dodge")+
  theme_bw()+
  facet_wrap(~language)+
  xlab("number of vowels")+
  ylab("number of words")+
  labs(title = "Number of vowels in Russian and English words",
          caption = "data is from http://ids.clld.org/")
```

```{r, echo = FALSE, warning= FALSE}
words_df %>%
  select(language, n_char) %>% 
  mutate(n_char = factor(n_char)) %>% 
  group_by(n_char, language) %>% 
  summarise(number = n()) %>% 
  spread(language, number) %>% 
  ggplot(aes(x = eng,y = rus, label = n_char))+
  geom_text()+
  theme_bw()+
  scale_x_log10()+
  scale_y_log10()+
  xlab("number of English words")+
  ylab("number of Russian words")+
  labs(title = "Word length in English and Russian",
       subtitle = "axes represent number of words with number of charaters represented by label",
          caption = "data is from http://ids.clld.org/")
```

