---
title: "Lab 8. Dummy variables. ANOVA"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

## [Assignment link](https://goo.gl/forms/IgIy6Kw3EWVcTi8y1)

```{r}
library(tidyverse)
```


### 1. 
```{r, echo= FALSE, eval= FALSE}
df <- read.csv("http://goo.gl/0btfKa")

df %>% 
  ggplot(aes(ejectives, n.cons.lapsyd, color = ejectives))+
  geom_jitter(width = 0.2)+
  labs(title = "Number of syllables ~ presence of ejectives",
       x = "presence of ejectives",
       y = "number of syllables")

df %>% 
  group_by(ejectives) %>% 
  summarise(mean(n.cons.lapsyd))

fit <- lm(n.cons.lapsyd~ejectives, data = df)
summary(fit)

fit$coefficients
```

### 2.
```{r, echo= FALSE, eval= FALSE}
df <- read.csv("https://goo.gl/7gIjvK")

df %>% 
  ggplot(aes(place, vowel.dur))+
  geom_boxplot(outlier.alpha = 0.2)+
  geom_point(alpha = 0.2)+
  labs(title = "Vowel duration by place of articulation",
       caption = "Data from (Coretta 2017)",
       x = "place of articulation",
       y = "vowel duration")

fit <- aov(vowel.dur~place, data = df)
summary(fit)
fit$coefficients

df %>% 
  group_by(place) %>% 
  summarise(mean(vowel.dur))
```


```{r, include=FALSE}
df <- read.csv("https://goo.gl/7gIjvK")
fit <- aov(vowel.dur~place, data = df)
```


```{r, echo= FALSE}
tk <- TukeyHSD(fit)
# fast visualization
plot(tk)

# ggplot
tk <- data.frame(tk$place)
tk$Comparison <- row.names(tk)

tk %>% 
  ggplot(aes(Comparison, y = diff, ymin = lwr, ymax = upr)) +
  geom_pointrange() +
  ylab("Difference in Mean levels of place of articulation") +
  coord_flip()
```

```{r, echo = FALSE, eval = FALSE}
m1 <- lm(cdi~tv.hours, data = tv)
summary(m1)
m2 <- lm(cdi~mot.education, data = tv)
summary(m2)
m3 <- lm(cdi~tv.hours+mot.education, data = tv)
summary(m3)
m4 <- lm(cdi~., data = tv[,-1])
summary(m4)
```

```{r, echo = FALSE}
tv %>% 
  ggplot(aes(tv.hours, cdi))+
  geom_smooth(method="lm")+
  geom_point()+
  facet_wrap(~tv$book.reading)
```

