---
title: "Lab 3 and 4 CI. T-tests. P-value"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Link to tasks](https://docs.google.com/forms/d/e/1FAIpQLSdoAvNkatvJbMR2srszxKo66vMKLxVcu3EmAYXDr7XEUo4URQ/viewform?c=0&w=1)

### 1.1 and 1.2
```{r, eval = FALSE}
install.packages("tidyverse")
```

```{r, message=F}
library(tidyverse)
homo <- read.csv("http://goo.gl/Zjr9aF")
homo %>% 
  group_by(orientation) %>%
  summarise(mean = mean(s.duration.ms),
            CI = 1.96*sd(s.duration.ms)/sqrt(length(s.duration.ms)))

```

### 1.3
```{r}
homo %>% 
  group_by(orientation) %>%
  summarise(mean = mean(s.duration.ms),
            CI = 1.96*sd(s.duration.ms)/sqrt(length(s.duration.ms))) %>% 
  ggplot(aes(orientation, mean))+
  geom_point()+
  geom_errorbar(aes(ymin= mean-CI,
                    ymax = mean+CI), width = 0.3)+
  labs(title = "Mean [s] duration with 95% confidence interval",
       caption = "Data from (Chi-kuk 2007)")

```



```{r}
library(tidyverse)
iris %>% 
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species))+
  geom_point(size = 5)+
  facet_wrap(~Species)
```

### 1.4
```{r}
homo %>% 
  ggplot(aes(s.duration.ms, fill = orientation)) +
  geom_density()+
  geom_rug()+
  facet_wrap(~orientation)+
  labs(title = "[s] duration density plot",
       caption = "Data from (Chi-kuk 2007)")
```

```{r}
homo %>% 
  ggplot(aes(s.duration.ms, fill = orientation)) +
  geom_density()+
  geom_rug(aes(color = orientation), size = 5)+
  facet_wrap(~orientation)+
  labs(title = "[s] duration density plot",
       caption = "Data from (Chi-kuk 2007)")
```

### 1.5

```{r}
t.test(s.duration.ms~orientation, data = homo)
```
p-value < 0.05...

[xkcd](https://xkcd.com/1478/):
If all else fails, use "significant at p > 0.05 level"; and hope no one notices (*it is a joke*)

### One-sample t-test
```{r}
df <- read.csv("http://goo.gl/TRRx9Y")
df[df$name == "russian", 2]
t.test(df[df$name == "russian", 2], mu = 240)
```

### Paired t-test
```{r}
df <- read.csv("http://goo.gl/MNkVws", sep="\t")
t.test(df$LI.Front, df$LI.Temp, paired = TRUE)
```
